variable "fwavs_name" {}
variable "firewall_name" {}
variable "fw_username" {}
variable "fw_password" {}
variable "storage_acct_name" {}
variable "vnet_name" {}
variable "address_space" {}
variable "mgmt_subnet" {}
variable "untrust_subnet" {}
variable "trust_subnet" {}
variable "dns_server" {}
variable "global_dns_server" {}
variable "resource_group_name" {}
variable "location" {}
variable "ilb_name" {}